language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"

cache:
  - apt

before_install:
  - python -m pip install --upgrade pip
  - pip install codecov pytest pytest-cov
  - sudo apt-get update
  - sudo apt-get -y install libxml2-dev
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - sudo apt-get -y install gcc-4.8
  - sudo apt-get install gnupg2
  - curl -L "https://download.sr-support.com/SRResearch_key" | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] http://download.sr-support.com/software SRResearch main"
  - sudo apt-get update
  - sudo apt-get install -y eyelink-edfapi
  - export C_INCLUDE_PATH="/usr/include/EyeLink:$C_INCLUDE_PATH"

install:
  - pip install pandas
  - pip install Cython
  - pip install h5py
  - git clone https://github.com/nwilming/pyedfread.git
  - cd pyedfread && python setup.py install && cd ..
  - pip install -r dev-requirements.txt

# command to run tests
script:
  - for d in bidsphysio.*; do pytest --cov=$d --cov-append $d; done

after_success:
  - codecov
