language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

cache:
  - apt

before_install:
  - python -m pip install --upgrade pip
  - pip install codecov pytest pytest-cov
  - apt-get update
  - apt-get -y install libxml2-dev
  - add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - apt-get -q update
  - apt-get -y install gcc-4.8

install:
  - pip install Cython
  - pip install h5py
  - git clone https://github.com/nwilming/pyedfread.git
  - cd pyedfread && python setup.py install
  - pip install -r dev-requirements.txt

# command to run tests
script:
  - for d in bidsphysio.*; do pytest --cov=$d --cov-append $d; done

after_success:
  - codecov
