language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

cache:
  - apt

before_install:
  - python -m pip install --upgrade pip
  - pip install codecov pytest pytest-cov
  - ./install_pyedfread.sh

install:
  - pip install -r dev-requirements.txt

# command to run tests
script:
  - for d in bidsphysio.*; do pytest --cov=$d --cov-append $d; done

after_success:
  - codecov
