language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

cache:
  - apt

before_install:
  - python -m pip install --upgrade pip
  - pip install codecov pytest pytest-cov
  - sudo apt-get update
  - sudo apt-get -y install libxml2-dev
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - sudo apt-get -y install gcc-4.8
  - curl -L "http://download.sr-support.com/software/dists/SRResearch/SRResearch_key" | sudo apt-key add -
  - add-apt-repository "deb http://download.sr-support.com/software SRResearch main"
  - sudo apt-get update
  - sudo apt-get install -y eyelink-display-software 

install:
  - pip install Cython
  - pip install h5py
  - git clone https://github.com/nwilming/pyedfread.git
  - cd pyedfread && python setup.py install
  - pip install -r dev-requirements.txt

# command to run tests
script:
  - for d in bidsphysio.*; do pytest --cov=$d --cov-append $d; done

after_success:
  - codecov
